#!/usr/bin/with-contenv bash

# This is an install script that is designed to run after init-mods-package-install
# so it can take advantage of packages installed
# init-mods-end depends on this script so that later init and services wait until this script exits

echo "**** Setting up Trusted Proxy ****"

if [ -f /config/configuration.yaml ]; then
    echo "**** found config, add trusted proxy ****"
    yq -i '.http.use_x_forwarded_for = True | .http.trusted_proxies[0] = strenv(PROXY_HOSTNAME)' /config/configuration.yaml
else
    echo "**** found NO config, add initial config files + trusted proxy ****"
    wget --directory-prefix "/config/" https://aseracorp.github.io/resiSTORE/servapps/HomeAssistant/artefacts/configuration.yaml
fi
if [ ! -f /config/automations.yaml ]; then
    echo "**** Missing file automations.yaml, downloading... ****"
    wget --directory-prefix "/config/" https://aseracorp.github.io/resiSTORE/servapps/HomeAssistant/artefacts/automations.yaml
fi
if [ ! -f /config/scenes.yaml ]; then
    echo "**** Missing file scenes.yaml, downloading... ****"
    wget --directory-prefix "/config/" https://aseracorp.github.io/resiSTORE/servapps/HomeAssistant/artefacts/scenes.yaml
fi
if [ ! -f /config/scripts.yaml ]; then
    echo "**** Missing file scripts.yaml, downloading... ****"
    wget --directory-prefix "/config/" https://aseracorp.github.io/resiSTORE/servapps/HomeAssistant/artefacts/scripts.yaml
fi