#!/usr/bin/with-contenv bash

# This is an install script that is designed to run after init-mods-package-install
# so it can take advantage of packages installed
# init-mods-end depends on this script so that later init and services wait until this script exits

echo "**** Setting up Trusted Proxy ****"

if [ -f /config/configuration.yaml ]; then
    echo "**** found config, add trusted proxy ****"
else
    echo "**** found NO config, add initial config files + trusted proxy ****"

    printf 'default_config:\ntts:\n  - platform: google_translate\nfrontend:\n  themes: !include_dir_merge_named themes\nautomation: !include automations.yaml\nscript: !include scripts.yaml\nscene: !include scenes.yaml' > /config/configuration.yaml

fi

if [[ $PROXY_HOSTNAME == "["*"]" ]]; then
    yq -i '.http.use_x_forwarded_for = true | .http.trusted_proxies = env(PROXY_HOSTNAME) | .http.trusted_proxies style="single"' /config/configuration.yaml
else
    yq -i '.http.use_x_forwarded_for = True | .http.trusted_proxies[0] = strenv(PROXY_HOSTNAME)' /config/configuration.yaml
fi

touch /config/automations.yaml
touch /config/scenes.yaml
touch /config/scripts.yaml